name: CI

on: 
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      - uses: ./bump-version
        id: version
        with:
          path: './VERSION'
          step: 'major'

      - run: docker build -t chtelf/hello-world-gitaction:${{ steps.version.outputs.value}} .
      - run: docker push chtelf/hello-world-gitaction:${{ steps.version.outputs.value}}
      - run: npm install
      - run: npm test